Add symbol tags as proposed for LSP specification (e.g. visibility tags, static, abstract, etc.) #977
eclipse/lsp4e pull request #1149
Opened 2024-11-22 11:34 UTC by travkin79

Start using new symbol tags as proposed in my https://github.com/microsoft/language-server-protocol/pull/2003, for example, adding private, package, protected, and public visibility tags as well as tags like static, final, abstract, read-only, nullable and non-null. Our motivation comes from our wish to add visibility and other symbol details to the outline view (see discussion https://github.com/eclipse/lsp4e/discussions/977), but maybe also to the call hierarchy and to the type hierarchy or to other related features / LSP operations.

The PR on the LSP specification requires at least one implementation in a language server and / or a client. We plan to finish a first language server implementation in clangd [[1](https://github.com/llvm/llvm-project/pull/113669)] [[2](https://github.com/llvm/llvm-project/pull/167536)] [[3](https://github.com/llvm/llvm-project/pull/170103)] and a first client implementation in LSP4J, LSP4E, and CDT LSP (which is using clangd).

See https://github.com/microsoft/language-server-protocol/pull/2003
and https://github.com/llvm/llvm-project/pull/167536
and https://github.com/eclipse-lsp4j/lsp4j/pull/856

The PR for updating LSP4E to LSP4J vers. 1.0.0 (#1421) has to be merged before this PR can be merged.

2024-11-22 12:41 UTC, rubenporras commented
This would be great it the LSP gets improved and a new version in released.

2025-11-12 18:13 UTC, sebthom commented
Hi @travkin79, just checking in - are you planning to finish this PR? It would be much appreciated if you could! 😊

2025-11-13 11:25 UTC, travkin79 commented
Hi @sebthom,
Yes, I'd be happy to finish this and related PRs.

The reason for the delay is that the LSP PR requires (in best case) a client implementation and a language server implementation. We planned to implement it for CDT LSP, LSP4E and clangd, but the person [implementing the required changes on clangd side](https://github.com/llvm/llvm-project/pull/113669) stopped working on her/his PR. But in the meanwhile, we found someone else who will finish the work. So, I hope to finish the related PRs, including this one, some time soon.

2025-11-25 13:33 UTC, travkin79 commented
Hi @jonahgraham, @sebthom, and @rubenporras,
It seems that LSP4J introduced some new `Either` types in the API vers. 1.0.0 and LSP4E didn't adapt the changes. Is someone working on that or can give me some hints how the new types should be handled in LSP4E?

Type changes in LSP4J vers. 1.0.0:
* `TextEdit `-> `Either<TextEdit, SnippetTextEdit>` in `TextDocumentEdit` class
* `String `-> `Either<String, MarkupContent>` in `Diagnostic `class

2025-11-25 13:36 UTC, jonahgraham commented on org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
> + org.eclipse.lsp4j.jsonrpc;bundle-version="[1.0.0,1.1.0)",
We have improved the [API policy](https://github.com/eclipse-lsp4j/lsp4j/blob/main/README.md#api-policy) for 1.0 going forward to be properly semantic versions. This means the range can safely be:


```suggestion
 org.eclipse.lsp4j.jsonrpc;bundle-version="[1.0.0,2.0.0)",
```

2025-11-25 14:40 UTC, travkin79 commented on org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
> + org.eclipse.lsp4j.jsonrpc;bundle-version="[1.0.0,1.1.0)",
Hi @jonahgraham,

> It may be a better idea to have a separate PR for the 0.24 -> 1.0 LSP4J change,...

Do we need an issue for the separate PR? I started PR #1421 for that purpose.

2025-11-25 14:59 UTC, jonahgraham commented on org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
> + org.eclipse.lsp4j.jsonrpc;bundle-version="[1.0.0,1.1.0)",
> Do we need an issue for the separate PR?

No IMHO - but I am not an active committer on LSP4E so I don't know if it is best to just create one to save yourself hassle later.

2025-11-25 15:51 UTC, travkin79 commented on org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
> + org.eclipse.lsp4j.jsonrpc;bundle-version="[1.0.0,1.1.0)",
OK. Then, @rubenporras, please let me know if you want me to create an issue for PR #1421 or if you prefer to create it yourself.

2025-11-27 13:54 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Hi @jonahgraham,
Do we have to dispose the images cached here? It seems that images should be disposed when the Display used to create them is being disposed. What would be the best way to do that?

2025-11-27 14:07 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				deprecatedImageDescriptor};
Hi @sebthom and @jonahgraham,
Is it correct here to use `@Nullable` this way? I want to express that the variable overlays cannot be `null`, but the array entries can be `null`.

2025-11-27 15:02 UTC, jonahgraham commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
The short answer is register with org.eclipse.swt.widgets.Display.disposeExec(Runnable) to dispose of images when the display is disposed.

You can also look at how org.eclipse.jface.resource.ImageRegistry handles it.

2025-11-27 15:04 UTC, jonahgraham commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				deprecatedImageDescriptor};
I think it is `@NonNull ImageDescriptor @Nullable []` - but not really very experienced in this area.

2025-11-27 15:07 UTC, jonahgraham commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
PS I dodged the "Do we have to dispose the images cached here? " part of the question - but the answer is yes in theory, in practice if the test suites aren't making additional displays, chances are it never matters in practice. However the non-dispose listener may warn about non-disposed images. Perhaps it is already on `colorToImageCache` entries, but as it happens on shutdown no one paid attention/noticed?

Run with `-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true` to get the warnings.

2025-11-27 17:13 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				deprecatedImageDescriptor};
That's what I also started with, but for some reason I get an error message saying that `@NonNull` is not allowed here. 🤔

2025-11-27 17:20 UTC, jonahgraham commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				deprecatedImageDescriptor};
I didn't try it - hopefully @sebthom has a good answer as he has been doing a great job of maintaining the nullness analysis.

2025-11-28 10:05 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				deprecatedImageDescriptor};
I think, I solved it now. It turns out, I erroneously used an annotation from LSP4J, not a JDT annotation. In addition, the null checks in Eclipse seem to have problems to correctly check nullabililty for array variables and their entries.

2025-11-28 12:41 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Ok, I hope to have solved it by disposing the cached images on bundle / plug-in stop. I tried to start Eclipse with `-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true`, but did not see any warning or error message if images were not disposed.

2025-12-08 12:48 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		declareRegistryImage(IMG_OVR_OVERRIDE, OVERLAY + "override_co.png"); //$NON-NLS-1$
For future-proofing LSP4E, I would prefer the svg versions of these overlay images, if you still have them lying around somewhere :)

2025-12-08 12:51 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		return switch (symbolTag) {
Can we make this switch and the one in `imageDescriptorOverlayFromSymbolTag` exhaustive by removing the default case? I recently made similar changes to the other switch statements in LSPImages. This way the compiler will warn us if future LSP4J versions add support for more tags for which we are missing images.

2025-12-08 12:53 UTC, FlorianKroiss commented on org.eclipse.lsp4e/icons/full/obj16/constructor@2x.png
I think that's a better image for the constructor than what we have now. Can you use the svg version here instead?

2025-12-08 13:03 UTC, FlorianKroiss commented on org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/LSPImagesTest.java
> +	}
```suggestion
	@ParameterizedTest
	@EnumSource(SymbolKind.class)
	public void testAllImagesForSymbolKindAvailable(SymbolKind kind) {
	    Image img = LSPImages.imageFromSymbolKind(kind);

	    assertNotNull(img);
	}
	
	@ParameterizedTest
	@EnumSource(SymbolTag.class)
	public void testAllOverlayImagesForSymbolTagAvailable(SymbolTag tag) {
	    ImageDescriptor descriptor = LSPImages.imageDescriptorOverlayFromSymbolTag(tag);
	    Image img = LSPImages.imageOverlayFromSymbolTag(tag);
	    
	    assertNotNull(descriptor);
	    assertNotNull(img);
	}
```

2025-12-08 15:15 UTC, travkin79 commented
Hi @FlorianKroiss,

Thank you for your improvement suggestions and welcome in the LSP4E team!

> @travkin79 I recently made some changes so that LSP4E uses mostly svg images (#1456). Can you please try to replace the pngs in this PR with their respective svg source?

I think, using SVG images has many advantages when handling various screen sizes, DPI, and zoom levels. Unfortunately, I don't have any SVG version of the images in this PR. They were all taken from other Eclipse plug-ins (like JDT, CDT, etc.) using the Plug-in Image Browser view. But I did not check yet if there are SVG versions available in the plug-ins' git repos. I'll try to find out.

2025-12-09 10:09 UTC, travkin79 commented on org.eclipse.lsp4e/icons/full/obj16/constructor@2x.png
There is no SVG version of this image. I created it by combining two png files. I think, it might be a better idea to use the method icon and add an overlay icon with the "C" to it as I suggest in this PR for other cases, e.g. adding overlays for public, private, static, and other attributes.

2025-12-10 09:31 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		declareRegistryImage(IMG_OVR_OVERRIDE, OVERLAY + "override_co.png"); //$NON-NLS-1$
I've found SVG images for most used overlay icons and created new SVG icons for some new overlay icons. Now, all overlay icons are using SVG images instead of PNG files.

2025-12-10 09:37 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		declareRegistryImage(IMG_OVR_OVERRIDE, OVERLAY + "override_co.png"); //$NON-NLS-1$
That's awesome. Thank you! I think you can delete the unused pngs now

2025-12-10 09:51 UTC, travkin79 commented on org.eclipse.lsp4e/icons/full/obj16/constructor@2x.png
I tried using the method icons and adding a constructor overlay icon instead of using a pre-defined constructor icons, but due to public image constants in LSPImages class LSP4E-dependant plug-ins might depend on our image in the image registry. Thus, I created a new SVG image instead having the method icon and the "C" letter in it. That should work in all cases.

2025-12-10 12:51 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		declareRegistryImage(IMG_OVR_OVERRIDE, OVERLAY + "override_co.png"); //$NON-NLS-1$
Done, at least for overlay icons. :-)

2026-01-23 16:42 UTC, travkin79 commented
I'd like to go on with finalizing this PR. The prototype creates overlay icons in the icon corners for various additional details if they are provided by the language server. This includes the element's visibility (public, private, etc.), if it is static, deprecated, etc. Here is an example:

<img width="387" height="196" alt="image" src="https://github.com/user-attachments/assets/c9c08a02-c7fd-48f5-9b9c-54fa0a54f504" />


I'd like to hear your opinion on using overlay icons in the upper left corner of each symbol icon in contrast to JDT using differently shaped and colored symbol icons (at least for methods and fields) to express the visibility (see similar outline view examples from CDT and JDT in the first comment in discussion #977 and see the table below). Is it ok to use a visibility overlay icon (in the top left corner) for each symbol kind image instead of creating unique images for each combination of symbol kind and visibility, similar to JDT?

Icons used in JDT (classes look like overlay icons are used, methods and field have visibility-dependent icons):
| Element | original icon | private | package visible (default) | protected | public |
| -- | -- | -- | -- | -- | -- |
| Class (same for interfaces and enums)  | <img width="16" height="16" alt="class_obj" src="https://github.com/user-attachments/assets/630d3067-decd-4d74-80a5-7675e79b159e" /> | <img width="16" height="16" alt="innerclass_private_obj" src="https://github.com/user-attachments/assets/fe3bbe4d-7105-4f77-bba9-2f9cf615e05b" /> | <img width="16" height="16" alt="innerclass_default_obj" src="https://github.com/user-attachments/assets/68c4bf64-a0ed-4922-9fdf-97c3eda01908" /> | <img width="16" height="16" alt="innerclass_protected_obj" src="https://github.com/user-attachments/assets/bf1bdf1a-0137-42e2-a3df-89800ee1da35" /> | <img width="16" height="16" alt="innerclass_public_obj" src="https://github.com/user-attachments/assets/7ad5029a-0c31-40eb-af2f-37ad7ed83194" /> |
| Method | - | <img width="16" height="16" alt="methpri_obj" src="https://github.com/user-attachments/assets/bfdce06d-f9ac-4e48-9bfd-f6ecec9ccbe5" /> | <img width="16" height="16" alt="methdef_obj" src="https://github.com/user-attachments/assets/caeb2ce2-23f5-4644-bbb4-f711f0ca4eeb" /> | <img width="16" height="16" alt="methpro_obj" src="https://github.com/user-attachments/assets/9e16c86d-e4d4-4539-8c11-a5fbecf7f00a" /> | <img width="16" height="16" alt="methpub_obj" src="https://github.com/user-attachments/assets/01d2cb27-1139-4daf-b094-d3ee461898e9" /> |
| Field | - | <img width="16" height="16" alt="field_private_obj" src="https://github.com/user-attachments/assets/c76c757f-b780-444b-ad51-2fb216772950" /> | <img width="16" height="16" alt="field_default_obj" src="https://github.com/user-attachments/assets/ae25cb36-84c0-4a1c-a70d-049c38f8ac11" /> | <img width="16" height="16" alt="field_protected_obj" src="https://github.com/user-attachments/assets/cc0b6fb9-3d32-4039-b847-5f4c8f57ada5" />  | <img width="16" height="16" alt="field_public_obj" src="https://github.com/user-attachments/assets/a5994caf-9acc-46c9-89b6-a3d7244dae91" /> |

2026-01-26 19:56 UTC, FlorianKroiss commented
I think that using an overlay in the top-left to indicate visibility is fine. It probably also makes future maintenance of this implementation easier.

I think that creating unique icons for each combination of symbolkind and visibilitytag is a lot of work, and also harder to maintain in the long run. The only benefit that this would get you, is that you free up the left corner to potentially display one more tag.

Disclaimer: I'm not a UI/UX person, so maybe my ideas here at not the best design decisions from a end-user perspective 😅

2026-01-31 17:22 UTC, FlorianKroiss reviewed
PR overall looks good. My comments are mostly suggestions/nitpicks but nothing which must be addressed.

If you have any questions on my comments, feel free to ask,

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/SymbolsUtil.java
> +		return deprecated || (symbolInformation.getDeprecated() == null ? false: symbolInformation.getDeprecated());
These checks are always a bit clumsy, but I would prefer this:
```suggestion
		return deprecated || Boolean.TRUE.equals(symbolInformation.getDeprecated());
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/SymbolsUtil.java
> +		return deprecated || (documentSymbol.getDeprecated() == null ? false: documentSymbol.getDeprecated());
Similar to above
```suggestion
		return deprecated || Boolean.TRUE.equals(documentSymbol.getDeprecated());
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
> +		if (element != null && symbolKind != null) {
There is already a preceding null check
```suggestion
		if (symbolKind != null) {
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +			SymbolTag.Internal, SymbolTag.File });
```suggestion
	private static final List<SymbolTag> VISIBILITY_PRECEDENCE = List.of(
			SymbolTag.Public, SymbolTag.Protected, SymbolTag.Package, SymbolTag.Private,
			SymbolTag.Internal, SymbolTag.File);
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +			SymbolTag.Declaration, SymbolTag.Definition });
```suggestion
	private static final List<SymbolTag> ADDITIONAL_TAGS_PRECEDENCE = List.of(
			SymbolTag.Static, SymbolTag.Abstract, SymbolTag.Virtual, SymbolTag.Final, SymbolTag.Sealed,
			SymbolTag.Synchronized, SymbolTag.Transient, SymbolTag.Volatile,
			SymbolTag.Nullable, SymbolTag.NonNull, SymbolTag.ReadOnly,
			SymbolTag.Declaration, SymbolTag.Definition);
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	}
Since you only need the "highest" visibility, you could also do:

```suggestion
	private static @Nullable SymbolTag getHighestVisibilitySymbolTag(List<SymbolTag> symbolTags) {
		return symbolTags.stream()
				.filter(tag -> VISIBILITY_PRECEDENCE.contains(tag))
				.min(Comparator.comparing(VISIBILITY_PRECEDENCE::indexOf)
				.orElse(null);
	}
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +				.sorted(new AdditionalSymbolTagComparator())
```suggestion
				.sorted(Comparator.comparing(ADDITIONAL_TAGS_PRECEDENCE::indexOf))
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		return null;
```suggestion
		return switch(severity){
		case IMarker.SEVERITY_ERROR -> LSPImages.getSharedImageDescriptor(ISharedImages.IMG_DEC_FIELD_ERROR);
		case IMarker.SEVERITY_WARNING -> LSPImages.getSharedImageDescriptor(ISharedImages.IMG_DEC_FIELD_WARNING);
		default -> null;
		}
```

2026-01-31 17:22 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
In theory it is possible, though unlikely, that you get a hash collision here, i.e., two different icon+overlays hashing to the same integer.

I would prefer to use a compound key here:
```java
private record SymbolData(SymbolKind kind, SymbolTag visibility, int severity, boolean deprecated, SymbolTag firstAdditional, SymbolTag secondAdditional){}

private static final Map<SymbolData, Image> overlayImagesCache = new HashMap<>();
```

You could then adapt `getImageFor()` and the methods that it calls, to just compute the parts of the key.
If the key is not in the cache, then `Image getImageWithOverlays(SymbolData data)` constructs the image only with the data from the key.

2026-02-02 15:36 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
> +		if (element != null && symbolKind != null) {
That's not completely correct. In line 130 there is an assignment `element = either.get();` that might make the value `null` after the `null` check.

2026-02-02 15:42 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
> +		if (element != null && symbolKind != null) {
@travkin79 Yes, sorry. I'm used to parameters being `final` :(

2026-02-02 15:54 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	}
Good improvement. I just would return an `Optional<SymbolTag>` instead of `@Nullable SymbolTag`.

2026-02-02 15:59 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		return null;
Much better. Thank you.

2026-02-02 16:36 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
I have to think about that. At the moment. my impression is that this solution makes the code more complicated and less flexible. I'd prefer to separate the logic deciding where to place certain overlay icons (translating symbol tags and other details to `ImageDescriptor`s and their positions) from the logic looking up or creating the images (keeping the symbol's details like symbol tags, deprecation flag, and severity out of the cache key). By separating these parts, IMHO, it would be easier to change the set of symbol tags (or other details) shown in overlay icons as well as changing their positions in future. Besides, the constructor `DecorationOverlayIcon(Image baseImage, ImageDescriptor[] overlaysArray)` requires an `Image` (the symbol's image) and the overlay icon `ImageDescriptor`s anyway, so I'd prefer to make the cache key somehow dependent from these arguments.

Though, I understand that a hash collision might cause problems. Maybe there is another way of solving that.

2026-02-02 16:41 UTC, travkin79 commented
Hi @FlorianKroiss,

> PR overall looks good. My comments are mostly suggestions/nitpicks but nothing which must be addressed.
> 
> If you have any questions on my comments, feel free to ask,

Thank you very much for your detailed and helpful review. I incorporated most of your suggestions. IMHO your suggestions definitely improve the code quality. I'm just not yet sure about the cache key that we should use.

Nevertheless, before finishing this PR, I think, we have to wait for the next LSP4J release, where the new symbol tags will be added which I use in this PR.

2026-02-02 16:55 UTC, travkin79 commented
Hi @FlorianKroiss,

Thank you for the feedback.

> I think that using an overlay in the top-left to indicate visibility is fine. It probably also makes future maintenance of this implementation easier.
> 
> I think that creating unique icons for each combination of symbolkind and visibilitytag is a lot of work, and also harder to maintain in the long run. The only benefit that this would get you, is that you free up the left corner to potentially display one more tag.
> 
> Disclaimer: I'm not a UI/UX person, so maybe my ideas here at not the best design decisions from a end-user perspective 😅

I talked about that with my team mates. Some of them find it useful to reduce the number of overlay icons per document symbol in order to reduce "pollution" in the UI / make the icon overlays less distracting. Our idea was not to create different icons for each combination of a symbol kind and visibility tags, but only for fields and method and their combinations with visibility tags (i.e. 8 icons in total), since fields and methods are the elements that we see in views like the outline view and call hierarchy view most often.

We might also think about not showing certain details from symbol tags at all, maybe removing declaration and definition overlay icons. But we're not sure about that.

2026-02-03 10:19 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
> +		if (element != null && symbolKind != null) {
Good point. Usually, even if the method parameters are not final, I never change an argument's value. In the original code (from main branch), there is already an assignment to the parameter, but I don't like that either. It's not obvious that the parameter value might change. So I adapted the code to make that more obvious and made the parameter final.

Making other method parameters final, too, revealed a second similar case where I changed the code in a similar way.

2026-02-03 10:51 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Hi @FlorianKroiss,
I think, we could alternatively use a combination of the image keywords used for image or image descriptor lookup (e.g. `public static final String IMG_OVR_PRIVATE = "IMG_OVR_PRIVATE";` in `LSPImages`) in a record that builds the combined map key. What do you think about the following two options:

Option A - first key stays the SymbolKind, second key is the new record

```java
private record OverlaysCombinedKey(String imgKeyTopLeft, String imgKeyTopRight,
		String imgKeyBottomLeft, String imgKeyBottomRight, String imgKeyUnderlay) { }
	
private static final Map<SymbolKind, Map<OverlaysCombinedKey, Image>> overlayImagesCache = new HashMap<>();
```

Option B - SymbolKind and overlay image keys combined in one record

```java
private record SymbolWithOverlaysCombinedKey(SymbolKind kind, String imgKeyTopLeft, String imgKeyTopRight,
		String imgKeyBottomLeft, String imgKeyBottomRight, String imgKeyUnderlay) { }
	
private static final Map<SymbolWithOverlaysCombinedKey, Image> overlayImagesCache = new HashMap<>();
```

This way I could keep the code deciding about overlay icon placement separated from the code looking up the images.

Another thought of mine is: Aren't hash collisions in our case extremely unlikely? Maybe, it's not worth it, handling that case at the cost of complicating the code (and probably also performance). Or do we (just) need a more reliable way of calculating the hash values, e.g. instead of calculating the hash values based on an array of ImageDescriptor objects, just use the keys (strings) used in the records mentioned above and their indices?

2026-02-08 10:59 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Hi @travkin79,
Your argument about logic separation makes sense. I actually had a similar separation in mind, though a slightly different one, i.e., let `getImageFor` decide what information uniquely defines an icon and let `getImageWithOverlays` decide how to build an icon from that information. I made a quick&dirty PR (on your PR-Branch) to better demonstrate what I had in mind: https://github.com/travkin79/lsp4e/pull/1/changes

Since the proposed key is only an internal contract between getImageFor and getImageWithOverlays, I don't think that this makes the code less flexible, because we are always free to adjust the components of the key.

You are also right about the risk of hash collisions being negligible. I guess what irked me more about using an Integer as a key is that it essentially gives up type safety to some degree and requires a comment which explains what this Integer actually represents (btw. I really appreciate that JavaDoc comment 👍)

If you want to proceed with your suggestion, I would go with Option B, as it avoids to two-step lookup on the key.

2026-02-09 17:59 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Hi @FlorianKroiss,
Thank you for your detailed answer and code changes in a PR. I think, I understand your idea. Though, there is one thing that IMHO still doesn't fit well. Using a combined map key like `SymbolData(SymbolKind kind, int severity, boolean deprecated, @Nullable SymbolTag visibility, @Nullable SymbolTag first, @Nullable SymbolTag second)` has the following limitations:
* The key doesn't explicitly cover overlay icon placement (which details will be represented in which icon corner?). So, the decision, in which corner the corresponding overlay icons will be placed, will have to be made after looking up an image in the cache. This is why I used an array of `@Nullable ImageDescriptor` as a key instead in the first place (each entry describes and image and a certain placement), but I "simplified" the key by replacing it with its hash value.
* In case of constructors, we'll need special handling. A constructor uses an icon with an overlay in it. In this case the the second additional symbol tag needs to be omitted and the first might need another corner to be placed into.
* In case, we would handle more symbols in a special way (likely fields and methods) like hiding certain details (maybe not showing declaration / definition overlay icons) or adapting the placement (e.g. if we use different field icons for different visibilities and will place overlay icons in a slightly different way), that wouldn't work with your kind of combined key.

These thoughts are leading me to a key like one of the following. I prefer cases 3 and 4.

1. `record ImageKey(SymbolKind kind, ImageDescriptor[] overlays)`
2. `record ImageKey(ImageDescriptor[] symbolAndOverlays)`
3. `record ImageKey(ImageDescriptor imgSymbol, ImageDescriptor ovrTopLeft, ImageDescriptor ovrTopRight, 		ImageDescriptor ovrBottomLeft, ImageDescriptor ovrBottomRight, ImageDescriptor underlay)`
4. `record ImageKey(String imgSymbol, String imgKeyTopLeft, String imgKeyTopRight, String imgKeyBottomLeft, String imgKeyBottomRight, String imgKeyUnderlay)`

However, using one of these combined keys will eventually lead to calculating a hash value for the key (in the `HashMap` code) and checking if it's contained in the cache (in our `HashMap`). So, it will not prevent hash collisions anyway. Or may I be missing some point?

Though, I think, using a record like in the above cases 3 and 4 make the code more readable / maintainable, since the key would be self-explaining. I'll try to incorporate these ideas into my PR and would appreciate another review from your side, @FlorianKroiss.

2026-02-10 14:40 UTC, rubenporras commented
@travkin79 , I was planning to do a release for LSP4E tomorrow. Or would you like for me to wait a bit longer so that this PR can go in? Is your idea to finish this one quickly?

2026-02-10 14:56 UTC, travkin79 commented
Hi @rubenporras,

Thank you very much for asking. Indeed, I would like to finish this PR quite soon, but I think, my PR might still need some final review. In addition, I don't want to unnecessarily delay any release.

Could we just create another LSP4E release a few days / weeks later? In that case you could just go on with preparing the LSP4E release tomorrow.

2026-02-10 15:15 UTC, rubenporras commented
Thanks. Let us then create a release now and another one later, that is something quick to do.

2026-02-11 19:46 UTC, FlorianKroiss approved these changes
LGTM, only a few minor points.

Do plan to still work on the TODOs in this PR or address them later?

Btw: I think this will be a great addition to the LSP and LSP4E :)

2026-02-11 19:46 UTC, FlorianKroiss commented on org.eclipse.lsp4e/icons/full/ovr16/vis_file_co.svg
I think that should be named `file_visible_co.svg`?

2026-02-11 19:46 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +		declareRegistryImage(IMG_OVR_FILE_VIS, OVERLAY + "file_visable_co.svg"); //$NON-NLS-1$
```suggestion
		declareRegistryImage(IMG_OVR_FILE_VIS, OVERLAY + "file_visible_co.svg"); //$NON-NLS-1$
```

2026-02-11 19:46 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LSPImages.java
> +	private static final Map<SymbolKind, Map<Integer, Image>> overlayImagesCache = new HashMap<>();
Fair points. I'm fine with the solution that you have chosen :)

2026-02-12 10:08 UTC, travkin79 commented
Hi @FlorianKroiss,

> Do plan to still work on the TODOs in this PR or address them later?
 
I was working on implementing visibility-dependent symbol icons for fields and methods, similar to JDT. In most cases that leads to less overlay icons used in the outline view (and call hierarchy / type hierarchy views), in other cases that allows us to show one more detail (`SymbolTag`) in overlay icons.

Instead of having many overlay icons in the outline view like here

<img width="387" height="196" alt="image" src="https://github.com/user-attachments/assets/ef31f6b5-d00c-4b8d-bb07-38f4d5c0e585" />

we'll now have an outline view like here (field and method visibility is represented by the symbol icon instead of an additional overlay icon, declaration and definition details are omitted)

<img width="385" height="194" alt="image" src="https://github.com/user-attachments/assets/cbe64f83-860f-4961-9bad-5bb541477d00" />

Now, we have the following visibility representing icons in LSP4E:
| | fall-back icon | private | package-visible | protected | public | internal | file-visible |
| -- | -- | -- | -- | -- | -- | -- | -- |
| Field | <img width="16" height="16" alt="field" src="https://github.com/user-attachments/assets/5a030cb9-a969-4d7a-a970-7b4e9d07071f" /> | <img width="16" height="16" alt="field_private_obj" src="https://github.com/user-attachments/assets/c76c757f-b780-444b-ad51-2fb216772950" /> | <img width="16" height="16" alt="field_default_obj" src="https://github.com/user-attachments/assets/ae25cb36-84c0-4a1c-a70d-049c38f8ac11" /> | <img width="16" height="16" alt="field_protected_obj" src="https://github.com/user-attachments/assets/cc0b6fb9-3d32-4039-b847-5f4c8f57ada5" />  | <img width="16" height="16" alt="field_public_obj" src="https://github.com/user-attachments/assets/a5994caf-9acc-46c9-89b6-a3d7244dae91" /> | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/dd1829fb-72aa-44f3-8338-e2cb8a07dda9" /> | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/640eece1-2cd8-4a7c-84b1-ee4deef022b7" /> |
| Method | <img width="16" height="16" alt="method" src="https://github.com/user-attachments/assets/dfae5d35-ac26-4a49-93ad-e537aea12bb9" /> | <img width="16" height="16" alt="methpri_obj" src="https://github.com/user-attachments/assets/bfdce06d-f9ac-4e48-9bfd-f6ecec9ccbe5" /> | <img width="16" height="16" alt="methdef_obj" src="https://github.com/user-attachments/assets/caeb2ce2-23f5-4644-bbb4-f711f0ca4eeb" /> | <img width="16" height="16" alt="methpro_obj" src="https://github.com/user-attachments/assets/9e16c86d-e4d4-4539-8c11-a5fbecf7f00a" /> | <img width="16" height="16" alt="methpub_obj" src="https://github.com/user-attachments/assets/01d2cb27-1139-4daf-b094-d3ee461898e9" /> | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/4bcd8521-5848-448d-a092-9e6e5e69438d" /> | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/83a2646a-580a-4c10-9ceb-9bf38e439356" /> |
| Constructor | <img width="16" height="16" alt="constructor" src="https://github.com/user-attachments/assets/98238389-df3d-4e11-b526-b6c0faf6117c" /> | <img width="16" height="16" alt="methpri_obj" src="https://github.com/user-attachments/assets/bfdce06d-f9ac-4e48-9bfd-f6ecec9ccbe5" />* | <img width="16" height="16" alt="methdef_obj" src="https://github.com/user-attachments/assets/caeb2ce2-23f5-4644-bbb4-f711f0ca4eeb" />* | <img width="16" height="16" alt="methpro_obj" src="https://github.com/user-attachments/assets/9e16c86d-e4d4-4539-8c11-a5fbecf7f00a" />* | <img width="16" height="16" alt="methpub_obj" src="https://github.com/user-attachments/assets/01d2cb27-1139-4daf-b094-d3ee461898e9" />* | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/4bcd8521-5848-448d-a092-9e6e5e69438d" />* | <img width="16" height="16" alt="image" src="https://github.com/user-attachments/assets/83a2646a-580a-4c10-9ceb-9bf38e439356" />* |
| Overlay icon | - | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/e8d0a726-c9f8-4f1f-9590-e123142c2ab5" /> | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/0d987c0e-293e-4c1a-94db-e477be7fb649" /> | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/f3738982-9fb2-4666-a870-565cc4814392" /> | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/0074e933-fbae-4297-9b8d-2de8c76dac50" /> | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/031ac43d-d6f8-48dd-9cc1-6df8a2a620b0" /> | <img width="7" height="8" alt="image" src="https://github.com/user-attachments/assets/cd7b3150-b205-4377-a71b-09b5af7968c7" /> |

\* with a "C" overlay icon in the upper right corner similar to the fall-back icon

While implementing that, I had to adapt the cache's `HashMap` key a little. In addition, when thinking about customizing the label providers' behavior for certain languages (e.g. showing a destructor overlay icon in CDT LSP), I decided to separate label-provider-related code from the `LSPImages` class and made most methods customizable by making them overridable (protected and non-static). All label providers in LSP4E are now sub-classes of a new abstract label provider class.

I hope, you and maybe other reviewers consider the changes as an improvement.

Now, I think, I'll clean up the code a little and then the PR should be ready.

2026-02-17 07:03 UTC, FlorianKroiss requested changes

2026-02-17 07:03 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
> +			return getImageFor(symbolKind, symbolTags, getMaxSeverity(actualElement));
That's a very nice simplification of the API :)

2026-02-17 07:03 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/AbstractLsp4eLabelProvider.java
> +public abstract class AbstractLsp4eLabelProvider extends LabelProvider {
I think it makes sense that you moved these methods outside of LSPImages.

However, I think that putting them in an abstract label provider comes with some problems:

- From your motivating example, if a user wants to use different icons, they would have to subclass CallHierarchyProvider, TypeHierarchyProvider and SymbolLabelProvider and override the methods from this class, which leads to a lot of code duplication.
- If a user wants to use these methods for other parts of their UI, for example in a ColumnLabelProvider (which is not a subtype of LabelProvider), they would have to do some ugly wrapping to make it work

For the sake of composition-over-inheritance, I would prefer something like this:
```java
public class SymbolProvider {
// methods from this class
}
```

Then we can add a configurable SymbolProvider field to CallHierarchyProvider, TypeHierarchyProvider and SymbolLabelProvider. Alternatively, we could keep this class and only use to configure the SymbolProvider?
If so, I would prefer a name like "AbstractLSPLabelProvider" to be more consistent with other classes in LSP4E.

Now, if a user wants to change symbol lookup, they only have to create a subclass of SymbolProvider and configure their labelprovider accordingly. Additionally, the lookup code can also be used outside of LabelProvider subclasses.

Thoughts?

2026-02-17 07:03 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/AbstractLsp4eLabelProvider.java
> +				SymbolTag.Internal, SymbolTag.File, SymbolTag.Private);
That creates a new List every time. Can we put that in a static field instead?

2026-02-17 07:03 UTC, FlorianKroiss commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/AbstractLsp4eLabelProvider.java
> +				SymbolTag.ReadOnly);
That creates a new List every time. Can we put that in a static field instead?

2026-02-17 08:44 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/AbstractLsp4eLabelProvider.java
> +public abstract class AbstractLsp4eLabelProvider extends LabelProvider {
Hi @FlorianKroiss,
Yes, these are very good points. I'll restructure that code so that we'll have a customizable `SymbolProvider` (maybe I'll choose another class name) that can be easily used in all `LabelProvider`s and other places as you described.

2026-02-17 16:20 UTC, travkin79 commented on org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/AbstractLsp4eLabelProvider.java
> +public abstract class AbstractLsp4eLabelProvider extends LabelProvider {
Done

2026-02-19 07:29 UTC, rubenporras commented
@travkin79 , shall I merge?

2026-02-20 08:10 UTC, travkin79 commented
Hi @rubenporras,
I'm not sure if someone else like @jonahgraham would like to do a review before merging. In addition, I'd like to check a few things, but I don't have access to my computer at the moment. Maybe, we should wait a few days.

2026-02-26 14:54 UTC, travkin79 commented
Thanks @jonahgraham,
I'm looking forward to releasing this feature in LSP4E and getting the LSP specification PR merged, too.

Unfortunately, I'm still waiting for getting access to my workstation again, where I'd like to run final tests. (After incorporating the last feedback from @FlorianKroiss I was not able to test it properly on my workstation where I have set up a patched clangd version for this PR). As soon as I'm able to run the final tests, we can merge this PR.

2026-03-27 16:55 UTC, travkin79 commented
Hi @rubenporras,
I finally got access to my workstation again and tested the last commits in this PR. Everything works as expected. I think, we can merge this PR now. Do you want me to rebase the changes first?

2026-03-30 06:49 UTC, rubenporras commented
Hi @travkin79 ,

Yes, I think that is a good idea. I will merge then if after rebasing all looks good.

2026-04-07 09:37 UTC, travkin79 commented
Hi @rubenporras,
I rebased and bumped the lsp4e version. Do you think, we can merge now? What do you think, when will there be a next LSP4E release?

2026-04-07 11:14 UTC, merged

2026-04-07 11:15 UTC, rubenporras commented
Hi @travkin79 ,

usually do not plan fix points for the releases, but if you want a new release with this, just let me know and I will do one.

2026-04-07 11:50 UTC, travkin79 commented
Hi @rubenporras,
Thank you very much. I'll check with my team mates if we need a release shortly.

2026-04-09 04:46 UTC, rubenporras commented
Hi @travkin79 ,

I did a release to deliver a fix with the previous one, so now your feature is available in latest LSP4E's release.

2026-04-09 08:28 UTC, travkin79 commented
Hi @rubenporras,
Great! Thank you very much.