Deprecate methods in LanguageServerAccessor allowing access to a LanguageServer
eclipse/lsp4e pull request #482
Opened 2023-02-21 15:16 UTC by rubenporras

a LanguageServer

2023-02-22 14:48 UTC, mickaelistria requested changes
Do we still use those in LSP4E? Usually removing all references inside the project is a requirement for proper deprecation.
Also, another rule we should try to follow is that all deprecated methods should have in their Javadoc an example or a snippet of how they should be replaced.

2023-02-22 17:27 UTC, rubenporras commented
I will add the documentation.

After all the PRs we did, not, we do not use them any longer, only in tests. Does it qualify as something we must also not do before setting them obsolete?

If I understand you right, if we do not use them and add documentation, this PR would make sense, right?

2023-02-22 17:37 UTC, mickaelistria commented
> After all the PRs we did, not, we do not use them any longer,

Good.
For `@Deprecated(forDeletion = true)` it is.

> only in tests. Does it qualify as something we must also not do before setting them obsolete?

Ideally yes.

> If I understand you right, if we do not use them and add documentation, this PR would make sense, right?

Yes.

2023-02-28 10:58 UTC, mickaelistria approved these changes

2023-02-28 11:09 UTC, merged