Disable LSP rename handler for Java file
eclipse/lsp4e pull request #494
Opened 2023-02-28 08:55 UTC by angelozerr

This PR disable LSP rename handler for Java file. 

The problem has been reported here https://github.com/jbosstools/jbosstools-quarkus/issues/199

The JBoss Quarkus maps the MicroProfile language server to a Java file. Once the plugin is installed, it is not possible to use `Alt+Shift+R` because I think there is a conflict between LSP4E and JDT which is really annoying.

I have never seen some language server which support rename in Java file, it is the reason why this PR disable rename handler for Java file.

2023-02-28 10:39 UTC, mickaelistria requested changes
We won't create a particular dependency in LSP4E between LSP4E and JDT. We need to find another solution.

2023-02-28 13:29 UTC, angelozerr commented
This problem is very annoying because when you install JBoss Quarkus, we loose the capability to use `Alt+Shift+R` in Java editor.

Instead of excluding JDT Java source, we could include only editor which is the generic editor. What do you think @mickaelistria ?

2023-02-28 18:19 UTC, angelozerr commented
@JessicaJHee I asked at https://github.com/microsoft/vscode-languageserver-node/issues/1198

2023-03-01 15:16 UTC, sbouchet commented
that's an already known issue : https://github.com/eclipse/lsp4e/issues/38#issuecomment-1399985169

2023-03-01 15:42 UTC, sbouchet commented
see also #38

2023-03-14 20:23 UTC, mickaelistria commented
I'm closing this in LSP4E, it's more properly actionable on JDT end: https://github.com/eclipse-platform/eclipse.platform.ui/issues/513#issuecomment-1468778600 , or even in the jbosstools-quarkus plugin to redefine the binding to force one over the other.

2023-03-14 20:23 UTC, closed without merging