Limit the maximum number of outline symbols to 5000 to avoid UI freezes
eclipse/lsp4e pull request #704
Opened 2023-06-21 19:53 UTC by sebthom

This PR addresses #703 by limiting the maximum number of elements rendered in the UI to 5000 elements.

2023-06-27 09:41 UTC, mickaelistria requested changes
Let's just wait for https://github.com/eclipse-platform/eclipse.platform.ui/pull/810

2023-06-27 10:23 UTC, sebthom commented
@mickaelistria another issue I realized is that the Language Server also takes a considerable amount of time to provide the list of outline symbols for large files. is there a way to tell the LS to limit the number of elements returned in that request?

https://github.com/eclipse/lsp4e/blob/9ad25d4828c1041014993695fa5d1d2684510fed/org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java#L316-L317

I can see that DocumentSymbolParams extends WorkDoneProgressAndPartialResultParams but it is not clear if the decision to return partial results can only be made by the server or also requested by the client.

2023-06-27 12:40 UTC, mickaelistria commented
I don't see anything that fits immediately in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ . I suggest you lookup in the issues reported against LSP, IIRC there was some discussion about "paginated" responses which could fit here.

2023-06-27 12:46 UTC, angelozerr commented
In LemMinx we have exactly this kind of problem (when we integrate LemMinx in vscode). It is the reason why we provide a custom limit for symbol.

> I don't see anything that fits immediately in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ .

Indeed but folding specifies rangeLimit, see 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange

So it can be a good idea to have too a rangeLimit kind for symbols.

Please note that symbol is used in breadcrumb in vscode, so I think symbols request should perhaps send too an information about the cursor location(just to give symbols hierachy for the cursor location).

2023-06-27 13:01 UTC, mickaelistria commented
Overall, LSP and more particularly JSON-RPC may be missing some capacity for sending responses in (ordered) chunks so that clients such as LSP4J could get the output as a stream or returning potentially long sequences in a BlockingQueue... But this problem is deeply rooted in JSon-RPC/LSP and should rather be addressed there.

2024-02-29 14:55 UTC, akurtakov commented
Is this still needed after platform.ui change?

2024-02-29 22:11 UTC, sebthom commented
A code change is still necessary because the platform.ui change is not enabled by default for all tables/tree viewers.

However this change does only address one part of the UI freeze. With newer lsp4j releases the following issue popped up eclipse-lsp4j/lsp4j#815

2024-03-08 11:12 UTC, ghentschke commented
I ran into performance issues as well. I think this PR is a good starting point. Can this be merged @mickaelistria ?

2024-03-08 11:28 UTC, rubenporras commented
Hi @ghentschke,  but would the problem not also greatly improved (also increasing performance in all cases) if we would fix https://github.com/eclipse/lsp4e/issues/907 without using experimental APIs? 

PD: If you agree to merge this PR, that is fine for me as well, regardless of what is the answer to my question.

2024-03-08 11:34 UTC, sebthom commented
> without using experimental APIs?

While the javadoc says it is experimental, it is actively used in eclipse.platform.ui and eclipse.jdt.ui so I doubt it is so experimental.

2024-03-08 11:37 UTC, ghentschke commented
IMO a better solution would  be lazy loading. Fetch the data in the background and update the treeview when the user scrolls. But this PR is a good starting to point to keep eclipse responsive.

2024-03-08 11:41 UTC, sebthom commented
> IMO a better solution would be lazy loading. Fetch the data in the background and update the treeview when the user scrolls. But this PR is a good starting to point to keep eclipse responsive.

I also suggested that in the platform issue but they somehow found the current solution better.

2024-03-08 12:08 UTC, mickaelistria approved these changes

2024-03-08 17:35 UTC, ghentschke commented
The next step would be to refactor the `org.eclipse.lsp4e.outline.LSSymbolsContentProvider` to support partial results as described [here](https://github.com/eclipse-lsp4j/lsp4j/issues/815)

2024-03-09 11:14 UTC, merged